name: relay_repo
description: "A centralized media vault app that lets users save or bookmark videos/posts from any platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  receive_sharing_intent: ^1.8.1
  metadata_fetch: ^0.4.2
  video_player: ^2.9.1
  chewie: ^1.8.3
  path_provider: ^2.1.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3


flutter:
  uses-material-design: true
  assets:
    - .env
